### ISSUE TITLE
Request location from friends

### ISSUE THREAD

**Issue by protist** [owntracks/owntracks#19]
I'm not sure if this is beyond the capabilities of OwnTracks, but it'd be very useful to be able to request an updated location from a friend. Sometimes, I find that their updating has been a bit slow, and I'm looking at position of my friend that is from hours ago.

I'm not sure how you feel about battery drain implications. Personally, I think it'd be *more* useful for me to be able to manually poll friends when necessary (e.g. every few weeks) rather than for them to have to automatically update their position on the scale of minutes.

**Comment by jpmens** [comment]
Thanks for your suggestion. It actually isn't a battery issue; rather an MQTT issue. MQTT isn't really suited for doing RPC (remote procedure calls). As such, the "request friend update" on one device would publish a request which the second device would see _at some later point in time_ and then react to.

We actually had this originally, but removed the feature because people were not understanding *why* the "request friend update" didn't happen *immediately*. In particular with iOS originally, and Android now, the apps are put to "sleep" in the background by the OS and make this near to useless.

I'll close this now.

**Comment by protist** [comment]
Thank you for the prompt and detailed reply. I don't understand enough about the Android infrastructure, but I would have thought that it should be possible to "wake up" the processes (or prevent sleep?). For example, [Prey](https://www.preyproject.com/) seems capable of making the phone do particular things at all times, even when sleeping. And I think Android Lost and MAXS can, as well.

Having said that, after my last post, I realised that my "friend's" phone hadn't updated in >24 hours yesterday, despite the notification still being present in the pull-down menu.

**Comment by jpmens** [comment]
While the apps no longer have anything in the interface for requesting remote location, they will still react to a request. You can issue a `reportLocation` command as described in the [Booklet](http://owntracks.org/booklet/tech/json/#_typecmd)

**Comment by protist** [comment]
Perhaps I misunderstand, but couldn't this request in theory be submitted by another OwnTracks client? Similar to how it works with Prey, etc.? Or are you saying that this request is also asynchronous?

**Comment by jpmens** [comment]
If by "OwnTracks client" you mean one of our apps, the answer is "it could", but we no longer do that. (There used to be a UI for that, but we removed it as for reasons mentioned above.) The request is async because you have something which publishes a request, and something else which, at some later point in time, reacts to the request. Try it with a `mosquitto_pub` and `_sub`. :-)

**Comment by protist** [comment]
Oh okay, I understand now. Thanks for all the information.

I just had one more quick question that is related. I'm happy to open a new issue, but it's probably something that you've already considered and rejected, so I'll leave it in this thread for now. 😬

The way I understand it, if a user is stationary, the OwnCloud app will *not* push any information to the server. However, I find reading that a bit ambiguous. If my app shows that my friend has not updated for x hours, then I'm not sure if they really *are* still in their last-reported position, or if their device has just stopped uploading data. Is there a reason why the app won't push their same position anyway? I'm presuming this is battery related, but I would have thought the location fix would be more power hungry compared to a small upload. Or I've just got it wrong again. 😛
